spring.application.name=demo2
server.port:9090

spring.datasource.username=root
spring.datasource.password=bca123
spring.datasource.url=jdbc:mysql://localhost:3306/springapp
spring.jpa.hibernate.ddl-auto=update